export let products = [
  {
    id: 1,
    title: "Camiseta Básica",
    price: 15.99,
    description: "Camiseta de algodón 100%, disponible en varios colores.",
    img: "https://example.com/camiseta_basica.jpg",
    stock: 100,
    category: "Camisetas",
  },
  {
    id: 2,
    title: "Camiseta Estampada",
    price: 18.99,
    description: "Camiseta con estampado divertido, hecha de algodón.",
    img: "https://example.com/camiseta_estampada.jpg",
    stock: 90,
    category: "Camisetas",
  },
  {
    id: 3,
    title: "Camiseta Deportiva",
    price: 22.99,
    description: "Camiseta deportiva de material transpirable.",
    img: "https://example.com/camiseta_deportiva.jpg",
    stock: 75,
    category: "Camisetas",
  },
  {
    id: 4,
    title: "Camiseta Manga Larga",
    price: 20.99,
    description: "Camiseta de manga larga para mayor confort.",
    img: "https://example.com/camiseta_manga_larga.jpg",
    stock: 80,
    category: "Camisetas",
  },
  {
    id: 5,
    title: "Camiseta Slim Fit",
    price: 19.99,
    description: "Camiseta ajustada para un look moderno.",
    img: "https://example.com/camiseta_slim_fit.jpg",
    stock: 65,
    category: "Camisetas",
  },
  {
    id: 6,
    title: "Camiseta V-Cut",
    price: 16.99,
    description: "Camiseta con cuello en V, perfecta para el verano.",
    img: "https://example.com/camiseta_v_cut.jpg",
    stock: 70,
    category: "Camisetas",
  },
  {
    id: 7,
    title: "Camiseta Oversize",
    price: 24.99,
    description: "Camiseta de estilo oversize para mayor comodidad.",
    img: "https://example.com/camiseta_oversize.jpg",
    stock: 50,
    category: "Camisetas",
  },
  {
    id: 8,
    title: "Camiseta Vintage",
    price: 26.99,
    description: "Camiseta con diseño vintage, hecha de algodón orgánico.",
    img: "https://example.com/camiseta_vintage.jpg",
    stock: 45,
    category: "Camisetas",
  },
  {
    id: 9,
    title: "Camiseta Rayada",
    price: 17.99,
    description:
      "Camiseta con rayas horizontales, disponible en varios colores.",
    img: "https://example.com/camiseta_rayada.jpg",
    stock: 85,
    category: "Camisetas",
  },
  {
    id: 10,
    title: "Camiseta Polo",
    price: 29.99,
    description: "Camiseta tipo polo con cuello y botones.",
    img: "https://example.com/camiseta_polo.jpg",
    stock: 55,
    category: "Camisetas",
  },
  {
    id: 11,
    title: "Pantalones Vaqueros",
    price: 49.99,
    description: "Pantalones vaqueros de corte recto y cintura alta.",
    img: "https://example.com/pantalones_vaqueros.jpg",
    stock: 50,
    category: "Pantalones",
  },
  {
    id: 12,
    title: "Pantalones Chinos",
    price: 39.99,
    description: "Pantalones chinos elegantes y cómodos.",
    img: "https://example.com/pantalones_chinos.jpg",
    stock: 60,
    category: "Pantalones",
  },
  {
    id: 13,
    title: "Pantalones Deportivos",
    price: 35.99,
    description: "Pantalones deportivos con cintura elástica.",
    img: "https://example.com/pantalones_deportivos.jpg",
    stock: 70,
    category: "Pantalones",
  },
  {
    id: 14,
    title: "Pantalones Cargo",
    price: 44.99,
    description: "Pantalones cargo con múltiples bolsillos.",
    img: "https://example.com/pantalones_cargo.jpg",
    stock: 55,
    category: "Pantalones",
  },
  {
    id: 15,
    title: "Pantalones de Vestir",
    price: 59.99,
    description: "Pantalones de vestir con corte slim.",
    img: "https://example.com/pantalones_vestir.jpg",
    stock: 40,
    category: "Pantalones",
  },
  {
    id: 16,
    title: "Pantalones Cortos",
    price: 19.99,
    description: "Pantalones cortos de mezclilla con dobladillo.",
    img: "https://example.com/pantalones_cortos.jpg",
    stock: 75,
    category: "Pantalones",
  },
  {
    id: 17,
    title: "Pantalones Jogger",
    price: 29.99,
    description: "Pantalones jogger de algodón, perfectos para el día a día.",
    img: "https://example.com/pantalones_jogger.jpg",
    stock: 65,
    category: "Pantalones",
  },
  {
    id: 18,
    title: "Pantalones Anchos",
    price: 32.99,
    description: "Pantalones anchos y cómodos, ideales para el verano.",
    img: "https://example.com/pantalones_anchos.jpg",
    stock: 50,
    category: "Pantalones",
  },
  {
    id: 19,
    title: "Pantalones Skinny",
    price: 42.99,
    description: "Pantalones skinny de mezclilla elástica.",
    img: "https://example.com/pantalones_skinny.jpg",
    stock: 55,
    category: "Pantalones",
  },
  {
    id: 20,
    title: "Pantalones Capri",
    price: 27.99,
    description: "Pantalones capri de estilo casual.",
    img: "https://example.com/pantalones_capri.jpg",
    stock: 60,
    category: "Pantalones",
  },
  {
    id: 21,
    title: "Abrigo de Lana",
    price: 120.0,
    description: "Abrigo de lana con solapa y cierre de botones.",
    img: "https://example.com/abrigo_lana.jpg",
    stock: 15,
    category: "Abrigos",
  },
  {
    id: 22,
    title: "Chaqueta de Cuero",
    price: 89.99,
    description: "Chaqueta de cuero auténtico con cierre de cremallera.",
    img: "https://example.com/chaqueta_cuero.jpg",
    stock: 20,
    category: "Abrigos",
  },
  {
    id: 23,
    title: "Chaqueta Vaquera",
    price: 59.99,
    description: "Chaqueta vaquera con bolsillos frontales.",
    img: "https://example.com/chaqueta_vaquera.jpg",
    stock: 25,
    category: "Abrigos",
  },
  {
    id: 24,
    title: "Abrigo Acolchado",
    price: 99.99,
    description: "Abrigo acolchado con capucha desmontable.",
    img: "https://example.com/abrigo_acolchado.jpg",
    stock: 18,
    category: "Abrigos",
  },
  {
    id: 25,
    title: "Parka de Invierno",
    price: 120.0,
    description: "Parka de invierno con forro térmico.",
    img: "https://example.com/parka_invierno.jpg",
    stock: 25,
    category: "Abrigos",
  },
  {
    id: 26,
    title: "Chaqueta Impermeable",
    price: 79.99,
    description: "Chaqueta impermeable con capucha ajustable.",
    img: "https://example.com/chaqueta_impermeable.jpg",
    stock: 20,
    category: "Abrigos",
  },
  {
    id: 27,
    title: "Gabardina Clásica",
    price: 110.0,
    description: "Gabardina clásica con cinturón y doble botonadura.",
    img: "https://example.com/gabardina_clasica.jpg",
    stock: 12,
    category: "Abrigos",
  },
  {
    id: 28,
    title: "Chaleco Acolchado",
    price: 55.99,
    description: "Chaleco acolchado con cierre de cremallera.",
    img: "https://example.com/chaleco_acolchado.jpg",
    stock: 25,
    category: "Abrigos",
  },
  {
    id: 29,
    title: "Abrigo de Pelo Sintético",
    price: 130.0,
    description: "Abrigo de pelo sintético suave y cálido.",
    img: "https://example.com/abrigo_pelo_sintetico.jpg",
    stock: 10,
    category: "Abrigos",
  },
  {
    id: 30,
    title: "Trenca con Capucha",
    price: 115.0,
    description: "Trenca clásica con capucha y cierre de alamar.",
    img: "https://example.com/trenca_capucha.jpg",
    stock: 15,
    category: "Abrigos",
  },
  {
    id: 31,
    title: "Vestido de Verano",
    price: 29.99,
    description: "Vestido de verano con estampado floral.",
    img: "https://example.com/vestido_verano.jpg",
    stock: 75,
    category: "Vestidos",
  },
  {
    id: 32,
    title: "Vestido de Noche",
    price: 89.99,
    description: "Vestido de noche elegante con detalles de encaje.",
    img: "https://example.com/vestido_noche.jpg",
    stock: 25,
    category: "Vestidos",
  },
  {
    id: 33,
    title: "Vestido Casual",
    price: 39.99,
    description: "Vestido casual de algodón, perfecto para el día a día.",
    img: "https://example.com/vestido_casual.jpg",
    stock: 60,
    category: "Vestidos",
  },
  {
    id: 34,
    title: "Vestido de Fiesta",
    price: 79.99,
    description: "Vestido de fiesta con lentejuelas y corte ajustado.",
    img: "https://example.com/vestido_fiesta.jpg",
    stock: 30,
    category: "Vestidos",
  },
  {
    id: 35,
    title: "Vestido Midi",
    price: 49.99,
    description: "Vestido midi con vuelo y estampado floral.",
    img: "https://example.com/vestido_midi.jpg",
    stock: 45,
    category: "Vestidos",
  },
  {
    id: 36,
    title: "Vestido Largo",
    price: 59.99,
    description: "Vestido largo con tirantes ajustables.",
    img: "https://example.com/vestido_largo.jpg",
    stock: 35,
    category: "Vestidos",
  },
  {
    id: 37,
    title: "Vestido de Encaje",
    price: 69.99,
    description: "Vestido de encaje con manga larga y corte ajustado.",
    img: "https://example.com/vestido_encaje.jpg",
    stock: 40,
    category: "Vestidos",
  },
  {
    id: 38,
    title: "Vestido de Punto",
    price: 54.99,
    description: "Vestido de punto suave y cómodo, ideal para el otoño.",
    img: "https://example.com/vestido_punto.jpg",
    stock: 50,
    category: "Vestidos",
  },
  {
    id: 39,
    title: "Vestido Estampado",
    price: 44.99,
    description: "Vestido con estampado geométrico y corte suelto.",
    img: "https://example.com/vestido_estampado.jpg",
    stock: 55,
    category: "Vestidos",
  },
  {
    id: 40,
    title: "Vestido Halter",
    price: 32.99,
    description: "Vestido halter con espalda descubierta.",
    img: "https://example.com/vestido_halter.jpg",
    stock: 60,
    category: "Vestidos",
  },
];
