export let products = [
  {
    title: "Camiseta Básica",
    price: 15.99,
    description: "Camiseta de algodón 100%, disponible en varios colores.",
    img: "https://goo.su/UEbw9",
    stock: 6,
    category: "Camisetas",
  },
  {
    title: "Camiseta Estampada",
    price: 18.99,
    description: "Camiseta con estampado divertido, hecha de algodón.",
    img: "https://goo.su/UEbw9",
    stock: 90,
    category: "Camisetas",
  },
  {
    title: "Camiseta Deportiva",
    price: 22.99,
    description: "Camiseta deportiva de material transpirable.",
    img: "https://goo.su/UEbw9",
    stock: 75,
    category: "Camisetas",
  },
  {
    title: "Camiseta Manga Larga",
    price: 20.99,
    description: "Camiseta de manga larga para mayor confort.",
    img: "https://goo.su/UEbw9",
    stock: 80,
    category: "Camisetas",
  },
  {
    title: "Camiseta Slim Fit",
    price: 19.99,
    description: "Camiseta ajustada para un look moderno.",
    img: "https://goo.su/UEbw9",
    stock: 65,
    category: "Camisetas",
  },
  {
    title: "Camiseta V-Cut",
    price: 16.99,
    description: "Camiseta con cuello en V, perfecta para el verano.",
    img: "https://goo.su/UEbw9",
    stock: 70,
    category: "Camisetas",
  },
  {
    title: "Camiseta Oversize",
    price: 24.99,
    description: "Camiseta de estilo oversize para mayor comodidad.",
    img: "https://goo.su/UEbw9",
    stock: 50,
    category: "Camisetas",
  },
  {
    title: "Camiseta Vintage",
    price: 26.99,
    description: "Camiseta con diseño vintage, hecha de algodón orgánico.",
    img: "https://goo.su/UEbw9",
    stock: 45,
    category: "Camisetas",
  },
  {
    title: "Camiseta Rayada",
    price: 17.99,
    description:
      "Camiseta con rayas horizontales, disponible en varios colores.",
    img: "https://goo.su/UEbw9",
    stock: 85,
    category: "Camisetas",
  },
  {
    title: "Camiseta Polo",
    price: 29.99,
    description: "Camiseta tipo polo con cuello y botones.",
    img: "https://goo.su/UEbw9",
    stock: 55,
    category: "Camisetas",
  },
  {
    title: "Pantalones Vaqueros",
    price: 49.99,
    description: "Pantalones vaqueros de corte recto y cintura alta.",
    img: "https://goo.su/J2bWz",
    stock: 50,
    category: "Pantalones",
  },
  {
    title: "Pantalones Chinos",
    price: 39.99,
    description: "Pantalones chinos elegantes y cómodos.",
    img: "https://goo.su/J2bWz",
    stock: 60,
    category: "Pantalones",
  },
  {
    title: "Pantalones Deportivos",
    price: 35.99,
    description: "Pantalones deportivos con cintura elástica.",
    img: "https://goo.su/J2bWz",
    stock: 70,
    category: "Pantalones",
  },
  {
    title: "Pantalones Cargo",
    price: 44.99,
    description: "Pantalones cargo con múltiples bolsillos.",
    img: "https://goo.su/J2bWz",
    stock: 55,
    category: "Pantalones",
  },
  {
    title: "Pantalones de Vestir",
    price: 59.99,
    description: "Pantalones de vestir con corte slim.",
    img: "https://goo.su/J2bWz",
    stock: 40,
    category: "Pantalones",
  },
  {
    title: "Pantalones Cortos",
    price: 19.99,
    description: "Pantalones cortos de mezclilla con dobladillo.",
    img: "https://goo.su/J2bWz",
    stock: 75,
    category: "Pantalones",
  },
  {
    title: "Pantalones Jogger",
    price: 29.99,
    description: "Pantalones jogger de algodón, perfectos para el día a día.",
    img: "https://goo.su/J2bWz",
    stock: 65,
    category: "Pantalones",
  },
  {
    title: "Pantalones Anchos",
    price: 32.99,
    description: "Pantalones anchos y cómodos, ideales para el verano.",
    img: "https://goo.su/J2bWz",
    stock: 50,
    category: "Pantalones",
  },
  {
    title: "Pantalones Skinny",
    price: 42.99,
    description: "Pantalones skinny de mezclilla elástica.",
    img: "https://goo.su/J2bWz",
    stock: 55,
    category: "Pantalones",
  },
  {
    title: "Pantalones Capri",
    price: 27.99,
    description: "Pantalones capri de estilo casual.",
    img: "https://goo.su/J2bWz",
    stock: 60,
    category: "Pantalones",
  },
  {
    title: "Abrigo de Lana",
    price: 120.0,
    description: "Abrigo de lana con solapa y cierre de botones.",
    img: "https://goo.su/FoZZC",
    stock: 15,
    category: "Abrigos",
  },
  {
    title: "Chaqueta de Cuero",
    price: 89.99,
    description: "Chaqueta de cuero auténtico con cierre de cremallera.",
    img: "https://goo.su/FoZZC",
    stock: 20,
    category: "Abrigos",
  },
  {
    title: "Chaqueta Vaquera",
    price: 59.99,
    description: "Chaqueta vaquera con bolsillos frontales.",
    img: "https://goo.su/FoZZC",
    stock: 25,
    category: "Abrigos",
  },
  {
    title: "Abrigo Acolchado",
    price: 99.99,
    description: "Abrigo acolchado con capucha desmontable.",
    img: "https://goo.su/FoZZC",
    stock: 18,
    category: "Abrigos",
  },
  {
    title: "Parka de Invierno",
    price: 120.0,
    description: "Parka de invierno con forro térmico.",
    img: "https://goo.su/FoZZC",
    stock: 25,
    category: "Abrigos",
  },
  {
    title: "Chaqueta Impermeable",
    price: 79.99,
    description: "Chaqueta impermeable con capucha ajustable.",
    img: "https://goo.su/FoZZC",
    stock: 20,
    category: "Abrigos",
  },
  {
    title: "Gabardina Clásica",
    price: 110.0,
    description: "Gabardina clásica con cinturón y doble botonadura.",
    img: "https://goo.su/FoZZC",
    stock: 12,
    category: "Abrigos",
  },
  {
    title: "Chaleco Acolchado",
    price: 55.99,
    description: "Chaleco acolchado con cierre de cremallera.",
    img: "https://goo.su/FoZZC",
    stock: 25,
    category: "Abrigos",
  },
  {
    title: "Abrigo de Pelo Sintético",
    price: 130.0,
    description: "Abrigo de pelo sintético para un look elegante.",
    img: "https://goo.su/FoZZC",
    stock: 10,
    category: "Abrigos",
  },
  {
    title: "Chaqueta de Pana",
    price: 79.99,
    description: "Chaqueta de pana con forro de borrego.",
    img: "https://goo.su/FoZZC",
    stock: 15,
    category: "Abrigos",
  },
];
